name: Automatic Model Training Workflow

on:
  push:
    branches:
      - main

jobs:
  experiment:
    name: Experiment Job
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Run the machine learning job
      working-directory: ./src
      run: az ml job create --file job.yml -g lab1 -w ML1

  production:
    name: Production Job
    runs-on: ubuntu-latest
    environment:
      name: dev
    needs: experiment
    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install az ml extension
      run: az extension add -n ml -y

    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}

    - name: Run the machine learning job
      working-directory: ./src
      run: az ml job create --file prod_job.yml -g lab1 -w ML1
