name: Runs on pull requests

on: [pull_request]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will hopefully add code checks here in next challenge"
  
